-- schema owner
CREATE USER basic WITH password 'basic';

-- schema user
CREATE USER basic_ms WITH password 'basic_ms';

-- create schema
CREATE SCHEMA basic AUTHORIZATION basic;

GRANT USAGE ON SCHEMA basic TO basic_ms;

ALTER DEFAULT PRIVILEGES FOR USER basic IN SCHEMA basic GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE ON TABLES TO basic_ms;
ALTER DEFAULT PRIVILEGES FOR USER basic IN SCHEMA basic GRANT USAGE ON SEQUENCES TO basic_ms;
ALTER DEFAULT PRIVILEGES FOR USER basic IN SCHEMA basic GRANT EXECUTE ON FUNCTIONS  TO basic_ms;